### ISSUE TITLE
Error in code_component_search on for statements with no (null) expressions.

### ISSUE THREAD

**Issue by Algomorph** [Algomorph/CodeGrader#129]
Where: Fall2021 CMSC132 P1 ranaya 

Error handling response: TypeError: Cannot read properties of null (reading 'node')
    at Object.findCodeComponentsInAstNode (chrome-extension://pbpjjhcjbinhnhehhhmflhpmgciaccco/code_analysis/code_component_search.js:27:25)
    at Object.findCodeComponentsInAstNode (chrome-extension://pbpjjhcjbinhnhehhhmflhpmgciaccco/code_analysis/code_component_search.js:315:22)
    at Object.findCodeComponentsInAstNode (chrome-extension://pbpjjhcjbinhnhehhhmflhpmgciaccco/code_analysis/code_component_search.js:315:22)
    at Object.findCodeComponentsInAstNode (chrome-extension://pbpjjhcjbinhnhehhhmflhpmgciaccco/code_analysis/code_component_search.js:315:22)
    at Object.findComponentsInCodeFileAst (chrome-extension://pbpjjhcjbinhnhehhhmflhpmgciaccco/code_analysis/code_component_search.js:333:22)
    at constructUiPanel (chrome-extension://pbpjjhcjbinhnhehhhmflhpmgciaccco/submit_server_main.js:114:27)
    at main (chrome-extension://pbpjjhcjbinhnhehhhmflhpmgciaccco/submit_server_main.js:64:13)
    at chrome-extension://pbpjjhcjbinhnhehhhmflhpmgciaccco/options.js:71:9

**Comment by Algomorph** [comment]
Fixed in c4e01c94fba2d0bb4d87fbe28854e8bd1746c0a3
