### ISSUE TITLE
Failures to load CodeGrader panel

### ISSUE THREAD

**Issue by goldburger** [Algomorph/CodeGrader#170]
Several different failures to load the part or all of CodeGrader panel.
Semester: Spring 2022
Instructor & Course: Pedram's CMSC132
Project name on Submit Server: Proj 6

Student directory id: azeng, bglobb
Behavior: panel does not load past classes/interfaces segment, console error as follows:
Error handling response: TypeError: Cannot read properties of undefined (reading 'start')
    at Object.getOperandStart (chrome-extension://pbpjjhcjbinhnhehhhmflhpmgciaccco/code_analysis/code_component_search.js:396:48)
    at Object.processCode (chrome-extension://pbpjjhcjbinhnhehhhmflhpmgciaccco/modules/spacing_module.js:165:66)
    at constructUiPanel (chrome-extension://pbpjjhcjbinhnhehhhmflhpmgciaccco/submit_server_main.js:133:20)
    at main (chrome-extension://pbpjjhcjbinhnhehhhmflhpmgciaccco/submit_server_main.js:66:13)
    at chrome-extension://pbpjjhcjbinhnhehhhmflhpmgciaccco/options.js:75:9

Student directory id: cjanssen
Behavior: Panel does not appear at all, console error as follows:
Error handling response: TypeError: Cannot read properties of undefined (reading 'start')
    at Object.findCodeComponentsInAstNode (chrome-extension://pbpjjhcjbinhnhehhhmflhpmgciaccco/code_analysis/code_component_search.js:315:107)
    at Object.findCodeComponentsInAstNode (chrome-extension://pbpjjhcjbinhnhehhhmflhpmgciaccco/code_analysis/code_component_search.js:321:22)
    at Object.findCodeComponentsInAstNode (chrome-extension://pbpjjhcjbinhnhehhhmflhpmgciaccco/code_analysis/code_component_search.js:321:22)
    at Object.findCodeComponentsInAstNode (chrome-extension://pbpjjhcjbinhnhehhhmflhpmgciaccco/code_analysis/code_component_search.js:321:22)
    at Object.findCodeComponentsInAstNode (chrome-extension://pbpjjhcjbinhnhehhhmflhpmgciaccco/code_analysis/code_component_search.js:321:22)
    at Object.findCodeComponentsInAstNode (chrome-extension://pbpjjhcjbinhnhehhhmflhpmgciaccco/code_analysis/code_component_search.js:328:22)
    at Object.findCodeComponentsInAstNode (chrome-extension://pbpjjhcjbinhnhehhhmflhpmgciaccco/code_analysis/code_component_search.js:321:22)
    at Object.findCodeComponentsInAstNode (chrome-extension://pbpjjhcjbinhnhehhhmflhpmgciaccco/code_analysis/code_component_search.js:328:22)
    at Object.findCodeComponentsInAstNode (chrome-extension://pbpjjhcjbinhnhehhhmflhpmgciaccco/code_analysis/code_component_search.js:321:22)
    at Object.findCodeComponentsInAstNode (chrome-extension://pbpjjhcjbinhnhehhhmflhpmgciaccco/code_analysis/code_component_search.js:328:22)

**Comment by Algomorph** [comment]
Thanks for reporting, I'll look into this shortly! There were some bugs associated with the latest code discovery changes for the class hierarchy analysis in method calls (for the testing module). This looks like it might be another latent bug like that.
