### ISSUE TITLE
Error in IndentationModule: line 170

### ISSUE THREAD

**Issue by Algomorph** [Algomorph/CodeGrader#56]
Case:
jallen30 / P7

Stack trace:
Error handling response: TypeError: Cannot read property 'length' of null
    at HTMLTableRowElement.<anonymous> (chrome-extension://njangockcidfcegiedkinajhaaeomldd/modules/indentation_module.js:170:77)
    at Function.each (chrome-extension://njangockcidfcegiedkinajhaaeomldd/third_party/jquery-3.5.1.min.js:2:2976)
    at Object.initialize (chrome-extension://njangockcidfcegiedkinajhaaeomldd/modules/indentation_module.js:67:11)
    at constructUiPanel (chrome-extension://njangockcidfcegiedkinajhaaeomldd/submit_server_main.js:119:28)
    at main (chrome-extension://njangockcidfcegiedkinajhaaeomldd/submit_server_main.js:51:13)

**Comment by msimmon6** [comment]
I think this was a duplicate of #25 since I'm not getting this.
